name: Terraform Deploy

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npx tsc

      - name: Generate ZIP to Lambda
        run: zip -r ./devops/terraform/lambda.zip dist node_modules package.json

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-west-2

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        working-directory: ./devops/terraform
        run: |
          export TF_LOG=DEBUG
          terraform init \ 
            -backend-config="bucket=${{ vars.TF_MAIN_BUCKET_NAME }}" \
            -backend-config="key=order-service/terraform.tfstate" \
            -backend-config="region=us-west-2" \
            -backend-config="encrypt=true"

      - name: Terraform Apply
        working-directory: ./devops/terraform
        run: terraform apply -auto-approve
